1-collector-json
Elen-B/plus-smart-home-tech pull request #1
Opened 2024-12-02 16:29 UTC by Elen-B

2024-12-03 16:55 UTC, z8q requested changes

2024-12-03 16:55 UTC, z8q commented on telemetry/collector/src/main/java/ru/practicum/config/KafkaConfig.java
> +        properties.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, valueSerializer);
не хватает CLIENT_ID_CONFIG

2024-12-03 16:55 UTC, z8q commented on telemetry/collector/src/main/java/ru/practicum/event/service/KafkaEventServiceImpl.java
> +        ProducerRecord<String, SpecificRecordBase> rec = new ProducerRecord<>(topic, specificRecordBase);
в ProducerRecord  можно еще указать метку времени события (timestamp.toEpochMilli()). Так как мы хотим, чтобы события в партиции были упорядочены по timestamp когда событие произошло, а не когда данные долетели до брокера кафки

2024-12-03 16:55 UTC, z8q commented on telemetry/collector/src/main/java/ru/practicum/event/service/KafkaEventServiceImpl.java
> +        ProducerRecord<String, SpecificRecordBase> rec = new ProducerRecord<>(topic, specificRecordBase);
Еще при отправке сообщений нужно указывать ключ (для наших двух топиков будет идентификатор хаба). Таким образом все события относящиеся к одному и тому же хабу (а значит к одному и тому же умному дому/квартире) будут попадать в одну партицию, а это значит что консьюмер гарантировано будет получать их в правильной очередности

партицию можно не указывать, передать null

2024-12-03 16:55 UTC, z8q commented on telemetry/collector/src/main/java/ru/practicum/config/KafkaConfig.java
> +    public static final String HUB_EVENTS_TOPIC = "telemetry.hubs.v1";
Можно попробовать избежать хардкода
создать класс с аннотацией `@ConfigurationProperties`, и тут, в конфиг-классе, объявить private final поле этого config property-класса

Над классом KafkaConfig еще поставить `@EnableConfigurationProperties(SomeConfigProperties.class)`

Это еще позволило бы не использовать Value аннотации

2024-12-03 16:57 UTC, z8q commented on telemetry/collector/src/main/resources/application.properties
> +kafka.topics.sensors=
можно было бы использовать

2024-12-04 06:27 UTC, Elen-B commented on telemetry/collector/src/main/resources/application.properties
> +kafka.topics.sensors=
Спасибо за ревью и рекомендации! С CLIENT_ID_CONFIG не очень разобралась, по какому принципу нужно задавать ид (в теории ничего нет, гугл тоже не очень помог). И есть сомнение, что правильно исправила получение топиков в KafkaEventServiceImpl

2024-12-04 19:16 UTC, z8q approved these changes

2024-12-05 07:23 UTC, merged