aggregator & analyzer
Elen-B/plus-smart-home-tech pull request #5
Opened 2024-12-16 17:57 UTC by Elen-B

2024-12-17 20:34 UTC, z8q requested changes

2024-12-17 20:34 UTC, z8q commented on telemetry/aggregator/src/main/java/ru/practicum/service/SnapshotService.java
> +    default void close() {}
планируется ли здесь логика?
в KafkaSnapshotServiceImpl.close есть обращение сюда, 
на случай, если что-то добавится?

2024-12-17 20:34 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/practicum/handler/hub/ScenarioAddedEventHandler.java
> +        Optional<Scenario> scenarioOpt = scenarioRepository.findByHubIdAndName(
тут еще предлагается взять sensorId со всех conditions и actions
scenarioAddedEventAvro.getConditions() - condition.getSensorId()
scenarioAddedEventAvro.getActions() - action.getSensorId()
проверить их на существование в SensorRepository

2024-12-17 20:34 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/practicum/handler/hub/ScenarioAddedEventHandler.java
> +        if (scenarioOpt.isEmpty()) {
Если сценарий существует, то у него нужно будет обновлять actions и conditions

2024-12-17 20:34 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/practicum/handler/hub/ScenarioAddedEventHandler.java
> +    public void handle(HubEventAvro hubEventAvro) {
в методе есть несколько обращений к базам, лучше провести одной транзакцией
поставить над методом `@Transactional`

2024-12-17 20:34 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/practicum/handler/hub/DeviceRemovedEventHandler.java
> +    public void handle(HubEventAvro hubEventAvro) {
Методы, которые работают с базой, лучше оборачивать в transactional

Пример возможных проблем, когда Transactional не используем над методом:
В таблице хранятся сущности, у которых есть lazy-поля
Мы делаем findAll по таблице и собираем список сущностей (транзакция для findAll открывается и сразу закрывается)
Дальше выполняем какую-нибудь логику с сущностями и сохраняем (Тут может возникать LazyInitializationException, если мы попытаемся обратиться к lazy полю. Потому что будет попытка подтянуть данные для этого поля из таблицы, но тразакция была закрыта сразу после вызова findAll, поэтому получим ошибку)

2024-12-17 20:34 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/practicum/handler/hub/DeviceRemovedEventHandler.java
> +            sensorRepository.deleteById(sensorId);
Можно поискать способы, которые свели  бы логику только к одному обращению к базе

2024-12-17 20:34 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/practicum/service/AnalyzerServiceImpl.java
> +    @Autowired
тут не совсем понял идею с autowired для репозитория
и со строкой в конструкторе
this.scenarioRepository = scenarioRepository;

2024-12-18 16:23 UTC, Elen-B commented on telemetry/aggregator/src/main/java/ru/practicum/service/SnapshotService.java
> +    default void close() {}
в интерфейсе не планировала логику, добавила метод как дефолтный, чтобы не было необходимости реализовывать его, если в другой будущей реализации интерфейса там ничего не должно быть. наверное, немного надуманно получилось

2024-12-18 16:50 UTC, Elen-B commented on telemetry/analyzer/src/main/java/ru/practicum/service/AnalyzerServiceImpl.java
> +    @Autowired
тут нет идеи 🤦, у меня не создавался бин и я пробовала разные варианты, ошибка конечно же была в другом

2024-12-18 19:34 UTC, z8q approved these changes

2024-12-18 19:34 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/practicum/handler/hub/ScenarioAddedEventHandler.java
> +        }
тут можно было бы объединить списки с sensorId в один, и одним запросом к базе отправить
но тогда будет сложнее вывести определенный лог
```
Не найдены сенсоры действий ...
Не найдены сенсоры условий ...
```

2024-12-18 19:34 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/practicum/handler/hub/ScenarioAddedEventHandler.java
>      }
возможно опечатка, что методы с большой буквы

2025-01-02 08:03 UTC, merged